// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs compare-xlsx`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "xlsx-viewer",
    "icon": "📗",
    "name": {
      "en": "Excel Workbook Viewer",
      "ja": "Excelビューア",
      "zh": "Excel 查看器",
      "de": "Excel-Arbeitsmappen-Viewer",
      "es": "Visor de libros de Excel"
    },
    "desc": {
      "en": "Open and browse an Excel workbook: switch sheets, no editing.",
      "ja": "Excelブックを開いて閲覧。シート切替、編集はしません。",
      "zh": "打开并浏览 Excel 工作簿，可切换工作表，不支持编辑。",
      "de": "Excel-Arbeitsmappe öffnen und ansehen, Blätter wechseln, keine Bearbeitung.",
      "es": "Abre y consulta un libro de Excel, cambia de hoja, sin edición."
    }
  },
  {
    "slug": "xlsx-to-csv",
    "icon": "📤",
    "name": {
      "en": "XLSX to CSV",
      "ja": "XLSX→CSV分割",
      "zh": "XLSX 转 CSV",
      "de": "XLSX zu CSV",
      "es": "XLSX a CSV"
    },
    "desc": {
      "en": "Split an Excel workbook into one CSV per sheet, zipped.",
      "ja": "Excelブックを1シート1CSVに分割してZIPで出力。",
      "zh": "将 Excel 工作簿按工作表拆分为多个 CSV，打包为 ZIP。",
      "de": "Teilt eine Excel-Arbeitsmappe in je eine CSV pro Blatt auf, als ZIP.",
      "es": "Divide un libro de Excel en un CSV por hoja, comprimido en ZIP."
    }
  },
  {
    "slug": "xlsx-merge",
    "icon": "🔗",
    "name": {
      "en": "Merge Excel Workbooks",
      "ja": "Excel統合",
      "zh": "合并 Excel 工作簿",
      "de": "Excel-Arbeitsmappen zusammenführen",
      "es": "Combinar libros de Excel"
    },
    "desc": {
      "en": "Merge every worksheet from multiple Excel workbooks into one.",
      "ja": "複数Excelブックの全シートを1つのブックに統合。",
      "zh": "将多个 Excel 工作簿的所有工作表合并为一个。",
      "de": "Führt alle Arbeitsblätter mehrerer Excel-Arbeitsmappen zu einer zusammen.",
      "es": "Combina todas las hojas de varios libros de Excel en uno solo."
    }
  },
  {
    "slug": "compare-text",
    "icon": "⚖️",
    "name": {
      "en": "Compare Text",
      "ja": "テキスト比較",
      "zh": "比较文本",
      "de": "Text vergleichen",
      "es": "Comparar texto"
    },
    "desc": {
      "en": "Diff two texts, line by line.",
      "ja": "2つのテキストを行単位で差分表示。",
      "zh": "逐行比较两段文本的差异。",
      "de": "Vergleiche zwei Texte Zeile für Zeile.",
      "es": "Compara dos textos línea por línea."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'compare-xlsx';
